/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rjsoft.cabure.gui.outros;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author jrpmaia
 */
public class SplashScreen extends javax.swing.JFrame {

    private Screen screen;
    private BufferedImage splash;
    private double progresso;

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        screen = new Screen();
        setContentPane(screen);
        progresso = 0.0;
        try {
            splash = ImageIO.read(getClass().getResourceAsStream("/splash.png"));
        } catch (Exception ex) {
            try {
                splash = ImageIO.read(getClass().getResourceAsStream("/resources/splash.png"));
            } catch (Exception ex2) {
            }
        }
        setUndecorated(true);
        setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setPreferredSize(new Dimension(splash.getWidth(), splash.getHeight()));
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(
                (int) screen.getWidth() / 2 - splash.getWidth() / 2,
                (int) screen.getHeight() / 2 - splash.getHeight() / 2);

        initComponents();
    }

    public void setProgresso(double p) {
//        progresso = p;
//        screen.paintComponent(splash.getGraphics());
//        screen.revalidate();
//        screen.repaint();
//        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private class Screen extends JPanel {

        public Screen() {
        }

//        @Override
//        public void paint(Graphics g) {
//            Graphics2D g2d = (Graphics2D) g;
//            super.paint(g2d);
//            g2d.drawImage(
//                    splash,
//                    0,
//                    0,
//                    null);
//            g2d.setColor(new Color(222, 170, 135));
//            double largura = 300;
//            g2d.fill(
//                    new Rectangle2D.Double(
//                            splash.getWidth() / 2 - largura / 2,
//                            splash.getHeight() - 22.5,
//                            largura,
//                            10
//                    )
//            );
//            g2d.setColor(new Color(80, 45, 22));
//            double n = largura * progresso;
//            g2d.fill(
//                    new Rectangle2D.Double(
//                            splash.getWidth() / 2 - largura / 2,
//                            splash.getHeight() - 22.5,
//                            n,
//                            10
//                    )
//            );
//        }
    
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2d = (Graphics2D) g;

            g2d.drawImage(
                    splash,
                    0,
                    0,
                    null);
//            g2d.setColor(new Color(222, 170, 135));
//            double largura = 300;
//            g2d.fill(
//                    new Rectangle2D.Double(
//                            splash.getWidth() / 2 - largura / 2,
//                            splash.getHeight() - 22.5,
//                            largura,
//                            10
//                    )
//            );
//            g2d.setColor(new Color(80, 45, 22));
//            g2d.fill(
//                    new Rectangle2D.Double(
//                            splash.getWidth() / 2 - largura / 2,
//                            splash.getHeight() - 22.5,
//                            largura * progresso,
//                            10
//                    )
//            );
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
