/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rjsoft.cabure.gui;

import com.rjsoft.cabure.gui.outros.BotaoIcone;
import com.rjsoft.cabure.gui.listeners.AcordeonListener;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;

/**
 *
 * @author jrpmaia
 */
public class Acordeon extends javax.swing.JPanel {

    private List<AcordeonListener> listeners;
    private boolean acordAluno;
    private boolean acordLivro;
    private boolean acordRelatorio;
    /**
     * Creates new form Acordeon
     */
    public Acordeon() {
        initComponents();
        listeners = new ArrayList();
        botCadAluno.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                botaoPressionado(AcordeonListener.BOT_CAD_ALUNO);
            }
        });
        botPesAlunos.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                botaoPressionado(AcordeonListener.BOT_PES_ALUNO);
            }
        });
        botCadLivro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                botaoPressionado(AcordeonListener.BOT_CAD_LIVRO);
            }
        });
        botPesLivros.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                botaoPressionado(AcordeonListener.BOT_PES_LIVRO);
            }
        });
    }

    public void addListener(AcordeonListener al) {
        listeners.add(al);
    }
    
    public void removeListener(AcordeonListener al) {
        listeners.remove(al);
    }
    
    private void botaoPressionado(int bot) {
        for (AcordeonListener al : listeners) {
            al.botaoAcordeonPressionado(bot);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botCadAluno = new javax.swing.JButton();
        botPesAlunos = new javax.swing.JButton();
        botCadLivro = new javax.swing.JButton();
        botPesLivros = new javax.swing.JButton();
        botRelatorioAlunos = new javax.swing.JButton();
        botRelatorioLivros = new javax.swing.JButton();
        botRelatorioEmprestimos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuInicio = new javax.swing.JButton();
        menuAluno = new javax.swing.JButton();
        menuLivro = new javax.swing.JButton();
        menuEmprestimo = new javax.swing.JButton();
        menuRelatorios = new javax.swing.JButton();

        botCadAluno.setBackground(new java.awt.Color(255, 255, 255));
        botCadAluno.setText("Cadastrar");
        botCadAluno = new BotaoIcone("Cadastrar", BotaoIcone.ICON_ADD, false);
        botCadAluno.setBackground(new java.awt.Color(200, 200, 200));
        botCadAluno.setMaximumSize(new java.awt.Dimension(1000, 32));

        botPesAlunos.setBackground(new java.awt.Color(255, 255, 255));
        botPesAlunos.setText("Pesquisar");
        botPesAlunos = new BotaoIcone("Pesquisar", BotaoIcone.ICON_PESQUISAR, false);
        botPesAlunos.setBackground(new java.awt.Color(200, 200, 200));
        botPesAlunos.setMaximumSize(new java.awt.Dimension(1000, 32));

        botCadLivro.setBackground(new java.awt.Color(255, 255, 255));
        botCadLivro.setText("Cadastrar");
        botCadLivro = new BotaoIcone("Cadastrar", BotaoIcone.ICON_ADD, false);
        botCadLivro.setBackground(new java.awt.Color(200, 200, 200));
        botCadLivro.setMaximumSize(new java.awt.Dimension(1000, 32));

        botPesLivros.setBackground(new java.awt.Color(255, 255, 255));
        botPesLivros.setText("Pesquisar");
        botPesLivros = new BotaoIcone("Pesquisar", BotaoIcone.ICON_PESQUISAR, false);
        botPesLivros.setBackground(new java.awt.Color(200, 200, 200));
        botPesLivros.setMaximumSize(new java.awt.Dimension(1000, 32));

        botRelatorioAlunos.setBackground(new java.awt.Color(255, 255, 255));
        botRelatorioAlunos.setText("Relatório Pessoas");
        botRelatorioAlunos.setMaximumSize(new java.awt.Dimension(1000, 32));
        botRelatorioAlunos = new BotaoIcone("Pessoas", BotaoIcone.ICON_RELATORIO_PESSOA, false);
        botRelatorioAlunos.setMaximumSize(new Dimension(1000, 32));
        botRelatorioAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRelatorioAlunosActionPerformed(evt);
            }
        });

        botRelatorioLivros.setBackground(new java.awt.Color(255, 255, 255));
        botRelatorioLivros.setText("Relatório Livros");
        botRelatorioLivros.setMaximumSize(new java.awt.Dimension(1000, 32));
        botRelatorioLivros = new BotaoIcone("Livros", BotaoIcone.ICON_RELATORIO_LIVRO, false);
        botRelatorioLivros.setMaximumSize(new Dimension(1000, 32));
        botRelatorioLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRelatorioLivrosActionPerformed(evt);
            }
        });

        botRelatorioEmprestimos.setBackground(new java.awt.Color(255, 255, 255));
        botRelatorioEmprestimos.setText("Relatório Empréstimos");
        botRelatorioEmprestimos.setMaximumSize(new java.awt.Dimension(1000, 32));
        botRelatorioEmprestimos = new BotaoIcone("Empréstimos", BotaoIcone.ICON_RELATORIO_EMPRESTIMO, false);
        botRelatorioEmprestimos.setMaximumSize(new Dimension(1000, 32));
        botRelatorioEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRelatorioEmprestimosActionPerformed(evt);
            }
        });

        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(200, 100));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 30));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        add(jPanel2);

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 135));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cabure_logomarca.png"))); // NOI18N
        jPanel1.add(jLabel1);

        add(jPanel1);

        menuInicio.setText("Inicio");
        menuInicio.setMargin(new java.awt.Insets(2, 2, 2, 2));
        menuInicio.setMaximumSize(new java.awt.Dimension(1000, 32));
        menuInicio.setMinimumSize(new java.awt.Dimension(0, 0));
        menuInicio = new BotaoIcone("Inicio", BotaoIcone.ICON_HOME, false);
        menuInicio.setMaximumSize(new Dimension(1000, 32));
        menuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicioActionPerformed(evt);
            }
        });
        add(Box.createRigidArea(new Dimension(1, 30)));
        add(menuInicio);

        menuAluno.setText("Pessoas");
        menuAluno.setMaximumSize(new java.awt.Dimension(1000, 32));
        menuAluno = new BotaoIcone("Pessoas", BotaoIcone.ICON_PESSOAS, true);
        menuAluno.setMaximumSize(new Dimension(1000, 32));
        menuAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlunoActionPerformed(evt);
            }
        });
        add(menuAluno);

        menuLivro.setText("Livros");
        menuLivro.setMaximumSize(new java.awt.Dimension(1000, 32));
        menuLivro = new BotaoIcone("Livros", BotaoIcone.ICON_LIVRO, true);
        menuLivro.setMaximumSize(new Dimension(1000, 32));
        menuLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLivroActionPerformed(evt);
            }
        });
        add(menuLivro);

        menuEmprestimo.setText("Empréstimos");
        menuEmprestimo.setMaximumSize(new java.awt.Dimension(1000, 32));
        menuEmprestimo = new BotaoIcone("Empréstimos", BotaoIcone.ICON_EMPRESTIMO, false);
        menuEmprestimo.setMaximumSize(new Dimension(1000, 32));
        menuEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmprestimoActionPerformed(evt);
            }
        });
        add(menuEmprestimo);

        menuRelatorios.setText("Relatórios");
        menuRelatorios.setMaximumSize(new java.awt.Dimension(1000, 32));
        menuRelatorios = new BotaoIcone("Relatórios", BotaoIcone.ICON_RELATORIO, true);
        menuRelatorios.setMaximumSize(new Dimension(1000, 32));
        menuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatoriosActionPerformed(evt);
            }
        });
        add(menuRelatorios);
    }// </editor-fold>//GEN-END:initComponents

    private void menuAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlunoActionPerformed
        acordAluno = !acordAluno;
        int index = getComponentZOrder(menuAluno);
        if (acordAluno) {
            add(botCadAluno, index + 1);
            add(botPesAlunos, index + 2);
        } else {
            remove(botCadAluno);
            remove(botPesAlunos);
        }
        revalidate();
    }//GEN-LAST:event_menuAlunoActionPerformed

    private void menuLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLivroActionPerformed
        acordLivro = !acordLivro;
        int index = getComponentZOrder(menuLivro);
        if (acordLivro) {
            add(botCadLivro, index + 1);
            add(botPesLivros, index + 2);
        } else {
            remove(botCadLivro);
            remove(botPesLivros);
        }
        revalidate();
    }//GEN-LAST:event_menuLivroActionPerformed

    private void menuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicioActionPerformed
        botaoPressionado(AcordeonListener.MENU_INICIO);
    }//GEN-LAST:event_menuInicioActionPerformed

    private void menuEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmprestimoActionPerformed
        botaoPressionado(AcordeonListener.MENU_EMPRESTIMO);
    }//GEN-LAST:event_menuEmprestimoActionPerformed

    private void botRelatorioAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRelatorioAlunosActionPerformed
        botaoPressionado(AcordeonListener.MENU_RELATORIO_ALUNOS);
    }//GEN-LAST:event_botRelatorioAlunosActionPerformed

    private void botRelatorioLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRelatorioLivrosActionPerformed
         botaoPressionado(AcordeonListener.MENU_RELATORIO_LIVROS);
    }//GEN-LAST:event_botRelatorioLivrosActionPerformed

    private void botRelatorioEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRelatorioEmprestimosActionPerformed
         botaoPressionado(AcordeonListener.MENU_RELATORIO_EMPRESTIMOS);
    }//GEN-LAST:event_botRelatorioEmprestimosActionPerformed

    private void menuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatoriosActionPerformed
        acordRelatorio = !acordRelatorio;
        int index = getComponentZOrder(menuRelatorios);
        if (acordRelatorio) {
            add(botRelatorioAlunos, index + 1);
            add(botRelatorioLivros, index + 2);
            add(botRelatorioEmprestimos, index + 3);
        } else {
            remove(botRelatorioAlunos);
            remove(botRelatorioLivros);
            remove(botRelatorioEmprestimos);
        }
        revalidate();
        repaint();
    }//GEN-LAST:event_menuRelatoriosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botCadAluno;
    private javax.swing.JButton botCadLivro;
    private javax.swing.JButton botPesAlunos;
    private javax.swing.JButton botPesLivros;
    private javax.swing.JButton botRelatorioAlunos;
    private javax.swing.JButton botRelatorioEmprestimos;
    private javax.swing.JButton botRelatorioLivros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton menuAluno;
    private javax.swing.JButton menuEmprestimo;
    private javax.swing.JButton menuInicio;
    private javax.swing.JButton menuLivro;
    private javax.swing.JButton menuRelatorios;
    // End of variables declaration//GEN-END:variables
}
