package com.rjsoft.cabure.gui;

import com.rjsoft.cabure.gui.listeners.AcordeonListener;
import com.rjsoft.cabure.controle.AlunoCtrl;
import com.rjsoft.cabure.controle.EmprestimoCtrl;
import com.rjsoft.cabure.controle.LivroCtrl;
import com.rjsoft.cabure.gui.listeners.TableListener;
import com.rjsoft.cabure.util.JPAUtil;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jrpmaia
 */
public class CabureGUI extends javax.swing.JFrame
        implements AcordeonListener, TableListener {

    /**
     * Creates new form Cabure
     */
    private HomePanel home;
    private CadastrarAlunoPanel cadastrarAluno;
    private PesquisarAlunoPanel pesquisarAluno;
    private CadastrarLivroPanel cadastrarLivro;
    private PesquisarLivroPanel pesquisarLivro;
    private GerenciarEmprestimosPanel gerenciarEmprestimos;
    private GerarRelatorioAlunoPanel relatorioAlunoPanel;
    private GerarRelatorioEmprestimoPanel relatorioEmprestimoPanel;
    private GerarRelatorioLivroPanel relatorioLivroPanel;
    private JPanel painelCentro;
    //Controles
    private AlunoCtrl alunoCtrl;
    private LivroCtrl livroCtrl;
    private EmprestimoCtrl emprestimoCtrl;
    private EmprestimoCtrl homeAtrasadosCtrl;
    private EmprestimoCtrl homeRealizadosCtrl;
    //Constantes
    private static final Dimension TAMANHO_MINIMO = new Dimension(600, 400);
    private static final Dimension TAMANHO_MAXIMO = new Dimension(800, 600);
    private static final String TITULO = "Cabure - Sistema de Gerenciamento de Biblioteca";

    public CabureGUI() {
        EntityManager em = JPAUtil.EMF.createEntityManager();
        alunoCtrl = new AlunoCtrl(em);
        livroCtrl = new LivroCtrl(em);
        emprestimoCtrl = new EmprestimoCtrl(em);
        homeAtrasadosCtrl = new EmprestimoCtrl(em);
        homeRealizadosCtrl = new EmprestimoCtrl(em);

        initComponents();

        home = new HomePanel(homeRealizadosCtrl, homeAtrasadosCtrl);
        cadastrarAluno = new CadastrarAlunoPanel(alunoCtrl);
        pesquisarAluno = new PesquisarAlunoPanel(alunoCtrl);
        cadastrarLivro = new CadastrarLivroPanel(livroCtrl);
        pesquisarLivro = new PesquisarLivroPanel(livroCtrl);
        relatorioAlunoPanel = new GerarRelatorioAlunoPanel(alunoCtrl);
        relatorioLivroPanel = new GerarRelatorioLivroPanel(livroCtrl,emprestimoCtrl);
        relatorioEmprestimoPanel = new GerarRelatorioEmprestimoPanel(emprestimoCtrl, livroCtrl, alunoCtrl);
        gerenciarEmprestimos = new GerenciarEmprestimosPanel(alunoCtrl, livroCtrl, emprestimoCtrl);

        home.pesquisarEA();
        home.pesquisarER();

        painelCentro = home;
        add(painelCentro, BorderLayout.CENTER);
        //Listeners
        acordeon1.addListener(this);
        pesquisarAluno.addTableListener(this);
        pesquisarLivro.addTableListener(this);
        setSize(TAMANHO_MAXIMO);
        setResizable(true);
        setMinimumSize(TAMANHO_MINIMO);
        setTitle(TITULO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        acordeon1 = new com.rjsoft.cabure.gui.Acordeon();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuIniciar = new javax.swing.JMenu();
        menuItemIniciar = new javax.swing.JMenuItem();
        menuAluno = new javax.swing.JMenu();
        menuItemCadAluno = new javax.swing.JMenuItem();
        menuItemPesAluno = new javax.swing.JMenuItem();
        menuLivro = new javax.swing.JMenu();
        menuItemCadLivro = new javax.swing.JMenuItem();
        menuItemPesLivro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemEmprestimos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemRelAlunos = new javax.swing.JMenuItem();
        menuItemLivros = new javax.swing.JMenuItem();
        menuItemRelEmprestimos = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        menuItemSobre = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(acordeon1, java.awt.BorderLayout.LINE_START);

        menuIniciar.setText("Inicio");
        menuIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIniciarActionPerformed(evt);
            }
        });

        menuItemIniciar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuItemIniciar.setText("Menu Inicial");
        menuItemIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIniciarActionPerformed(evt);
            }
        });
        menuIniciar.add(menuItemIniciar);

        jMenuBar1.add(menuIniciar);

        menuAluno.setText("Aluno");

        menuItemCadAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuItemCadAluno.setText("Cadastrar Aluno");
        menuItemCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadAlunoActionPerformed(evt);
            }
        });
        menuAluno.add(menuItemCadAluno);

        menuItemPesAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuItemPesAluno.setText("Pesquisar Aluno");
        menuItemPesAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPesAlunoActionPerformed(evt);
            }
        });
        menuAluno.add(menuItemPesAluno);

        jMenuBar1.add(menuAluno);

        menuLivro.setText("Livro");

        menuItemCadLivro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuItemCadLivro.setText("Cadastrar Livro");
        menuItemCadLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadLivroActionPerformed(evt);
            }
        });
        menuLivro.add(menuItemCadLivro);

        menuItemPesLivro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuItemPesLivro.setText("Pesquisar Livro");
        menuItemPesLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPesLivroActionPerformed(evt);
            }
        });
        menuLivro.add(menuItemPesLivro);

        jMenuBar1.add(menuLivro);

        jMenu2.setText("Empréstimos");

        menuItemEmprestimos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menuItemEmprestimos.setText("Verificar Empréstimos");
        menuItemEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmprestimosActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemEmprestimos);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Relatórios");

        menuItemRelAlunos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        menuItemRelAlunos.setText("Relatório de Alunos");
        menuItemRelAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelAlunosActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemRelAlunos);

        menuItemLivros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        menuItemLivros.setText("Relatório de Livros");
        menuItemLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLivrosActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemLivros);

        menuItemRelEmprestimos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        menuItemRelEmprestimos.setText("Relatório de Empréstimos");
        menuItemRelEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelEmprestimosActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemRelEmprestimos);

        jMenuBar1.add(jMenu1);

        menuSobre.setText("Sobre");

        menuItemSobre.setText("Informações");
        menuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSobreActionPerformed(evt);
            }
        });
        menuSobre.add(menuItemSobre);

        jMenuBar1.add(menuSobre);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemPesLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPesLivroActionPerformed
        botaoAcordeonPressionado(AcordeonListener.BOT_PES_LIVRO);
    }//GEN-LAST:event_menuItemPesLivroActionPerformed

    private void menuItemCadLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadLivroActionPerformed
        botaoAcordeonPressionado(AcordeonListener.BOT_CAD_LIVRO);
    }//GEN-LAST:event_menuItemCadLivroActionPerformed

    private void menuItemPesAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPesAlunoActionPerformed
        botaoAcordeonPressionado(AcordeonListener.BOT_PES_ALUNO);
    }//GEN-LAST:event_menuItemPesAlunoActionPerformed

    private void menuItemCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadAlunoActionPerformed
        botaoAcordeonPressionado(AcordeonListener.BOT_CAD_ALUNO);
    }//GEN-LAST:event_menuItemCadAlunoActionPerformed

    private void menuIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuIniciarActionPerformed

    private void menuItemIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIniciarActionPerformed
        botaoAcordeonPressionado(AcordeonListener.MENU_INICIO);
    }//GEN-LAST:event_menuItemIniciarActionPerformed

    private void menuItemEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmprestimosActionPerformed
        botaoAcordeonPressionado(AcordeonListener.MENU_EMPRESTIMO);
    }//GEN-LAST:event_menuItemEmprestimosActionPerformed

    private void menuItemRelAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelAlunosActionPerformed
        botaoAcordeonPressionado(AcordeonListener.MENU_RELATORIO_ALUNOS);
    }//GEN-LAST:event_menuItemRelAlunosActionPerformed

    private void menuItemLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLivrosActionPerformed
        botaoAcordeonPressionado(AcordeonListener.MENU_RELATORIO_LIVROS);
    }//GEN-LAST:event_menuItemLivrosActionPerformed

    private void menuItemRelEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelEmprestimosActionPerformed
        botaoAcordeonPressionado(AcordeonListener.MENU_RELATORIO_EMPRESTIMOS);
    }//GEN-LAST:event_menuItemRelEmprestimosActionPerformed

    private void menuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSobreActionPerformed
        JOptionPane.showMessageDialog(this, 
                "Sistema de Gerenciamento de Bibliotecas - Caburé\n"
                        + "Desenvolvedores:\n"
                        + "        Rummenigge Maia\n"
                        + "        Jaedson Araújo", 
                "Sobre o sistema Caburé", 
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItemSobreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rjsoft.cabure.gui.Acordeon acordeon1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuAluno;
    private javax.swing.JMenu menuIniciar;
    private javax.swing.JMenuItem menuItemCadAluno;
    private javax.swing.JMenuItem menuItemCadLivro;
    private javax.swing.JMenuItem menuItemEmprestimos;
    private javax.swing.JMenuItem menuItemIniciar;
    private javax.swing.JMenuItem menuItemLivros;
    private javax.swing.JMenuItem menuItemPesAluno;
    private javax.swing.JMenuItem menuItemPesLivro;
    private javax.swing.JMenuItem menuItemRelAlunos;
    private javax.swing.JMenuItem menuItemRelEmprestimos;
    private javax.swing.JMenuItem menuItemSobre;
    private javax.swing.JMenu menuLivro;
    private javax.swing.JMenu menuSobre;
    // End of variables declaration//GEN-END:variables

    private void setPainelCentro() {

        add(painelCentro, BorderLayout.CENTER);
        revalidate();
        repaint();
    }

    @Override
    public void botaoAcordeonPressionado(int botao) {
        remove(painelCentro);
        switch (botao) {
            case AcordeonListener.MENU_INICIO: {
                home.pesquisarEA();
                home.pesquisarER();
                painelCentro = home;
                break;
            }
            case AcordeonListener.BOT_CAD_ALUNO: {
                painelCentro = cadastrarAluno;
                break;
            }
            case AcordeonListener.BOT_PES_ALUNO: {
                pesquisarAluno.pesquisar();
                painelCentro = pesquisarAluno;
                break;
            }
            case AcordeonListener.BOT_CAD_LIVRO: {
                painelCentro = cadastrarLivro;
                break;
            }
            case AcordeonListener.BOT_PES_LIVRO: {
                pesquisarLivro.pesquisar();
                painelCentro = pesquisarLivro;
                break;
            }
            case AcordeonListener.MENU_EMPRESTIMO: {
                painelCentro = gerenciarEmprestimos;
                break;
            }
            case AcordeonListener.MENU_RELATORIO_ALUNOS: {
                painelCentro = relatorioAlunoPanel;
                break;
            }
            case AcordeonListener.MENU_RELATORIO_LIVROS: {
                painelCentro = relatorioLivroPanel;
                break;
            }
            case AcordeonListener.MENU_RELATORIO_EMPRESTIMOS: {
                painelCentro = relatorioEmprestimoPanel;
                break;
            }
            default: {
                home.pesquisarEA();
                home.pesquisarER();
                painelCentro = home;
            }
        }
        setPainelCentro();
    }

    @Override
    public void linhaSelecionada(int fonte, int idEntidade) {
        if (fonte == TableListener.TELA_PES_ALUNO) {
            remove(painelCentro);
            cadastrarAluno.carregarAluno(idEntidade);
            painelCentro = cadastrarAluno;
            setPainelCentro();
        } else if (fonte == TableListener.TELA_PES_LIVRO) {
            remove(painelCentro);
            cadastrarLivro.carregarLivro(idEntidade);
            painelCentro = cadastrarLivro;
            setPainelCentro();
        } 
    }
}
