/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rjsoft.cabure.gui;

import com.rjsoft.cabure.controle.AlunoCtrl;
import com.rjsoft.cabure.modelo.Aluno;
import java.util.List;
import javafx.scene.control.RadioButton;

/**
 *
 * @author JAEDSON
 */
public class GerarRelatorioAlunoPanel extends javax.swing.JPanel {

    /**
     * Creates new form RelatorioPanel
     */
    private AlunoCtrl ctrl;
    
    public GerarRelatorioAlunoPanel(AlunoCtrl ctrl) {
        this.ctrl = ctrl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoRelatorio = new javax.swing.ButtonGroup();
        buttonGroupTipoSituacaoAluno = new javax.swing.ButtonGroup();
        buttonGerarRelatorioAluno = new javax.swing.JButton();
        labelRelatorioAlunos = new javax.swing.JLabel();
        labelTipoRelatorio = new javax.swing.JLabel();
        radioButtonTipoSimplificado = new javax.swing.JRadioButton();
        radioButtonTipoCompleto = new javax.swing.JRadioButton();
        radioButtonSituacaoTodas = new javax.swing.JRadioButton();
        radioButtonSituacaoAtivos = new javax.swing.JRadioButton();
        radioButtonSituacaoInativos = new javax.swing.JRadioButton();
        labelSituacao = new javax.swing.JLabel();
        labelErrTipoRelatorio = new javax.swing.JLabel();
        labelErrTipoSituacao = new javax.swing.JLabel();

        buttonGerarRelatorioAluno.setText("Gerar Relatório");
        buttonGerarRelatorioAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGerarRelatorioAlunoActionPerformed(evt);
            }
        });

        labelRelatorioAlunos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelRelatorioAlunos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRelatorioAlunos.setText("Relatório de Alunos");
        labelRelatorioAlunos.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelTipoRelatorio.setText("Selecione o tipo de relatório:");

        buttonGroupTipoRelatorio.add(radioButtonTipoSimplificado);
        radioButtonTipoSimplificado.setText("Simplificado");

        buttonGroupTipoRelatorio.add(radioButtonTipoCompleto);
        radioButtonTipoCompleto.setText("Completo");

        buttonGroupTipoSituacaoAluno.add(radioButtonSituacaoTodas);
        radioButtonSituacaoTodas.setText("Todas as situações (Ativo e Inativo)");

        buttonGroupTipoSituacaoAluno.add(radioButtonSituacaoAtivos);
        radioButtonSituacaoAtivos.setText("Ativos");

        buttonGroupTipoSituacaoAluno.add(radioButtonSituacaoInativos);
        radioButtonSituacaoInativos.setText("Inativos");

        labelSituacao.setText("Selecione o tipo de situação do Aluno:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRelatorioAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTipoRelatorio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelErrTipoRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioButtonTipoSimplificado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButtonTipoCompleto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioButtonSituacaoTodas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButtonSituacaoAtivos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButtonSituacaoInativos))
                            .addComponent(buttonGerarRelatorioAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSituacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelErrTipoSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRelatorioAlunos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTipoRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelErrTipoRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonTipoSimplificado)
                    .addComponent(radioButtonTipoCompleto))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelErrTipoSituacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSituacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonSituacaoTodas)
                    .addComponent(radioButtonSituacaoAtivos)
                    .addComponent(radioButtonSituacaoInativos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonGerarRelatorioAluno)
                .addContainerGap(419, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGerarRelatorioAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGerarRelatorioAlunoActionPerformed
        if (validacao()){
            List<Aluno> listaAlunos = ctrl.pesquisarRelatorioAluno(gerarCondicao());
            
        }
    }//GEN-LAST:event_buttonGerarRelatorioAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGerarRelatorioAluno;
    private javax.swing.ButtonGroup buttonGroupTipoRelatorio;
    private javax.swing.ButtonGroup buttonGroupTipoSituacaoAluno;
    private javax.swing.JLabel labelErrTipoRelatorio;
    private javax.swing.JLabel labelErrTipoSituacao;
    private javax.swing.JLabel labelRelatorioAlunos;
    private javax.swing.JLabel labelSituacao;
    private javax.swing.JLabel labelTipoRelatorio;
    private javax.swing.JRadioButton radioButtonSituacaoAtivos;
    private javax.swing.JRadioButton radioButtonSituacaoInativos;
    private javax.swing.JRadioButton radioButtonSituacaoTodas;
    private javax.swing.JRadioButton radioButtonTipoCompleto;
    private javax.swing.JRadioButton radioButtonTipoSimplificado;
    // End of variables declaration//GEN-END:variables

    private boolean validacao() {
       boolean valido = true;
       if((radioButtonSituacaoAtivos.isSelected() == false) && 
               (radioButtonSituacaoInativos.isSelected() == false) &&
               (radioButtonSituacaoTodas.isSelected() == false)) {
            valido = false;
            labelErrTipoSituacao.setText("* Tipo de relatório obrigatório.");
       }
       if((radioButtonTipoCompleto.isSelected() == false) && 
               (radioButtonTipoSimplificado.isSelected() == false)){
           valido = false;                        
           labelErrTipoSituacao.setText("* Tipo de situação obrigatório.");
       }
       
       return valido;
    }
    
    private String gerarCondicao() {
        String condicao = "";
        
        if (radioButtonSituacaoAtivos.isSelected()) {
            condicao += String.format(" a.situacao = 'b'", true);
        }
        if (radioButtonSituacaoInativos.isSelected()){
            condicao += String.format(" a.situacao = 'b'", false);
        }
        if (radioButtonSituacaoTodas.isSelected()){
            // faz nada já que será o *
        }
        
        return condicao;
    }
}
